---
apiVersion: v1
kind: Service
metadata:
  name: nsm-registry-proxy-dns-svc
spec:
  selector:
    app: nsm-registry-proxy-dns
  ports:
    - name: nsm-registry-proxy-dns
      protocol: TCP
      port: 5003
      targetPort: 5003
