---
apiVersion: v1
kind: Service
metadata:
  namespace: nsm-system
  name: nsm-registry-svc
spec:
  selector:
    app: nsm-registry
  ports:
    - name: nsm-registry-svc
      protocol: TCP
      port: 5002
      targetPort: 5002
