---
apiVersion: v1
kind: Service
metadata:
  name: nsm-registry-service
spec:
  selector:
    app: nsm-registry
  ports:
    - name: registry
      protocol: TCP
      port: 5002
      targetPort: 5002
